package com.myspace.events;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class caseStatusBO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "CASESTATUSBO_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "CASESTATUSBO_ID_SEQ", name = "CASESTATUSBO_ID_GENERATOR")
    private java.lang.Long id;

    public caseStatusBO() {
    }
    
    public caseStatusBO(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}