package com.myspace.events;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class eventBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EVENTBO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EVENTBO_ID_SEQ", name = "EVENTBO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("contact")
	private java.lang.String contact;

	@org.kie.api.definition.type.Label("address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label("status")
	private java.lang.Boolean status;

	@org.kie.api.definition.type.Label("isReopened")
	private java.lang.Boolean isReopened;

	@org.kie.api.definition.type.Label("caseStatus")
	private String caseStatus;

	public eventBO() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getContact() {
		return this.contact;
	}

	public void setContact(java.lang.String contact) {
		this.contact = contact;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public java.lang.Boolean getIsReopened() {
		return this.isReopened;
	}

	public void setIsReopened(java.lang.Boolean isReopened) {
		this.isReopened = isReopened;
	}

	public java.lang.String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(java.lang.String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public eventBO(java.lang.Long id, java.lang.String name,
			java.lang.String contact, java.lang.String address,
			java.lang.Boolean status, java.lang.Boolean isReopened,
			java.lang.String caseStatus) {
		this.id = id;
		this.name = name;
		this.contact = contact;
		this.address = address;
		this.status = status;
		this.isReopened = isReopened;
		this.caseStatus = caseStatus;
	}

}